In [ ]:
# 📌 Tensor Manipulations & Reshaping with TensorFlow

import tensorflow as tf

# 1️⃣ Create a random tensor of shape (4, 6)
tensor = tf.random.uniform(shape=(4, 6))
print("Original Tensor:\n", tensor)

# 2️⃣ Find its rank and shape using TensorFlow functions
rank = tf.rank(tensor)
shape = tf.shape(tensor)
print("\nRank of original tensor:", rank.numpy())
print("Shape of original tensor:", shape.numpy())

# 3️⃣ Reshape it into (2, 3, 4)
reshaped_tensor = tf.reshape(tensor, (2, 3, 4))
print("\nReshaped Tensor (2, 3, 4):\n", reshaped_tensor)

# Transpose it to (3, 2, 4)
transposed_tensor = tf.transpose(reshaped_tensor, perm=[1, 0, 2])
print("Transposed Tensor (3, 2, 4):\n", transposed_tensor)

# 4️⃣ Broadcast a smaller tensor (1, 4) to match the larger tensor and add them
small_tensor = tf.constant([[1.0, 2.0, 3.0, 4.0]])  # Shape: (1, 4)
broadcasted_tensor = tf.broadcast_to(small_tensor, shape=(3, 2, 4))
print("\nBroadcasted Tensor (3, 2, 4):\n", broadcasted_tensor)

# Perform addition
result = transposed_tensor + broadcasted_tensor
print("Result after Addition:\n", result)


Original Tensor:
 tf.Tensor(
[[0.45912254 0.2961545  0.3522054  0.08382297 0.5438416  0.9693885 ]
 [0.19878614 0.31665885 0.47493386 0.84028554 0.8792926  0.54431903]
 [0.6900742  0.09686124 0.09430027 0.91156566 0.95636916 0.0046593 ]
 [0.15906489 0.7990134  0.04981637 0.3007598  0.36582255 0.07607543]], shape=(4, 6), dtype=float32)

Rank of original tensor: 2
Shape of original tensor: [4 6]

Reshaped Tensor (2, 3, 4):
 tf.Tensor(
[[[0.45912254 0.2961545  0.3522054  0.08382297]
  [0.5438416  0.9693885  0.19878614 0.31665885]
  [0.47493386 0.84028554 0.8792926  0.54431903]]

 [[0.6900742  0.09686124 0.09430027 0.91156566]
  [0.95636916 0.0046593  0.15906489 0.7990134 ]
  [0.04981637 0.3007598  0.36582255 0.07607543]]], shape=(2, 3, 4), dtype=float32)
Transposed Tensor (3, 2, 4):
 tf.Tensor(
[[[0.45912254 0.2961545  0.3522054  0.08382297]
  [0.6900742  0.09686124 0.09430027 0.91156566]]

 [[0.5438416  0.9693885  0.19878614 0.31665885]
  [0.95636916 0.0046593  0.15906489 0.7990134 ]]

 [